# Generated by Django 3.2.15 on 2022-09-09 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(max_length=100)),
                ('dis_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.distric')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='user',
            name='Village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.village'),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.distric'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.state'),
        ),
        migrations.AddField(
            model_name='distric',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.state'),
        ),
    ]
