# Generated by Django 3.2.15 on 2022-09-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_auto_20220909_0751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distric',
            new_name='District',
        ),
    ]
